<!--
  BackpropTrace.vue — Lecture 2, Chapter 4 (the worked example).

  One 2-2-2 network, seven stages, driven by the `stage` prop. Every number
  comes from the frozen V table below, which is generated by
  scripts/verify-numbers.py and cross-checked against PyTorch autograd.
  If a number here disagrees with that script, THIS FILE is wrong.

  CLICK CONTRACT
  Reveals are absolute v-click indices starting at `from` (default 1).
  This deliberately differs from NeuronDiagram.vue, which starts at
  v-click="2" and so burns the first key press on nothing. Because these
  v-click directives live inside a child component, Slidev cannot auto-count
  them: every slide using this component MUST set `clicks: N` in frontmatter.
  The required N for each stage is printed in STAGES below — read it there,
  do not guess.

  READING THE DIAGRAM (taught once on the setup slide, then relied on)
    above a neuron   = net, the weighted sum        teal   (forward)
    inside a neuron  = out, the activation          ink
    below a neuron   = delta, the blame             ember  (backward)
    chip to the right= bias
    on an edge       = the weight (teal) and, in backward stages,
                       that weight's gradient (ember)
-->
<template>
  <div class="bptrace" :class="{ 'is-compact': compact }">
    <svg :viewBox="`0 0 900 ${H}`" xmlns="http://www.w3.org/2000/svg">

      <!-- ============ edges ============ -->
      <g stroke="var(--ann-ink-soft)" stroke-width="2" style="opacity:0.5">
        <line v-for="e in EDGES" :key="e.k" :x1="e.x1" :y1="e.y1" :x2="e.x2" :y2="e.y2" />
      </g>

      <!-- highlighted edges for the neuron currently under discussion -->
      <g v-for="e in EDGES" :key="'hl-' + e.k">
        <line v-if="lit(e.k)" :x1="e.x1" :y1="e.y1" :x2="e.x2" :y2="e.y2"
              :stroke="litColor" stroke-width="4" stroke-linecap="round" />
      </g>

      <!-- ============ input + target squares (data, not computation) ============ -->
      <!-- split so that squares already on screen carry no directive at all,
           and squares that arrive on a click carry an absolute v-click -->
      <g v-for="n in INPUTS.filter(q => q.click === null)" :key="'sq-' + n.k">
        <rect :x="n.x - 26" :y="n.y - 26" width="52" height="52" rx="8"
              fill="var(--ann-paper-raised)" stroke="var(--ann-ink-soft)" stroke-width="2" style="opacity:0.85" />
        <text :x="n.x" :y="n.y + 6" class="val ink" text-anchor="middle">{{ n.v }}</text>
        <text :x="n.x" :y="n.y + 44" class="cap" text-anchor="middle">{{ n.lbl }}</text>
      </g>
      <g v-for="n in INPUTS.filter(q => q.click !== null)" :key="'sqc-' + n.k" v-click="n.click">
        <rect :x="n.x - 26" :y="n.y - 26" width="52" height="52" rx="8"
              fill="var(--ann-paper-raised)" stroke="var(--ann-ink-soft)" stroke-width="2" style="opacity:0.85" />
        <text :x="n.x" :y="n.y + 6" class="val ink" text-anchor="middle">{{ n.v }}</text>
        <text :x="n.x" :y="n.y + 44" class="cap" text-anchor="middle">{{ n.lbl }}</text>
      </g>

      <!-- ============ neurons ============ -->
      <g v-for="n in NEURONS" :key="n.k">
        <circle :cx="n.x" :cy="n.y" r="34"
                fill="var(--ann-paper-raised)"
                stroke="var(--ann-ink)" stroke-width="2.5"
                :style="{ opacity: dimmed(n.k) ? 0.4 : 0.9 }" />
        <text :x="n.x" :y="n.y - 44" class="nname" text-anchor="middle"
              :style="{ opacity: dimmed(n.k) ? 0.35 : 1 }">{{ n.lbl }}</text>
      </g>

      <!-- ============ annotations already on screen when the slide loads ============ -->
      <g v-for="a in baseAnnos" :key="'b-' + a.k" :style="{ opacity: a.dim ? 0.48 : 1 }">
        <rect v-if="a.chip" :x="a.x - a.w / 2" :y="a.y - 13" :width="a.w" height="24" rx="5"
              :fill="a.fill" :stroke="a.stroke" :stroke-dasharray="a.dash" stroke-width="1.5" />
        <text :x="a.x" :y="a.y + 5" :class="['val', a.cls]" text-anchor="middle">{{ a.t }}</text>
      </g>

      <!-- ============ annotations revealed by click ============ -->
      <g v-for="a in clickAnnos" :key="'c-' + a.k" v-click="a.click">
        <rect v-if="a.chip" :x="a.x - a.w / 2" :y="a.y - 13" :width="a.w" height="24" rx="5"
              :fill="a.fill" :stroke="a.stroke" :stroke-dasharray="a.dash" stroke-width="1.5" />
        <text :x="a.x" :y="a.y + 5" :class="['val', a.cls]" text-anchor="middle">{{ a.t }}</text>
      </g>

      <!-- ============ the loss box, parked at the right ============ -->
      <g v-if="lossBox" v-click="lossBox.click">
        <rect x="726" y="12" width="162" height="50" rx="8"
              fill="var(--ann-indigo-soft)" stroke="var(--ann-indigo)" stroke-width="2" />
        <text x="807" y="32" class="cap ind" text-anchor="middle">TOTAL LOSS</text>
        <text x="807" y="52" class="val upd" text-anchor="middle">{{ lossBox.t }}</text>
      </g>

      <!-- ============ "you are here" progress strip ============ -->
      <g v-if="showStrip">
        <g v-for="(s, i) in STRIP" :key="s">
          <rect :x="30 + i * 104" :y="H - 22" width="96" height="15" rx="4"
                :fill="i === stripIndex ? 'var(--ann-indigo)' : 'var(--ann-paper-raised)'"
                :stroke="i === stripIndex ? 'var(--ann-indigo)' : 'var(--ann-line)'" stroke-width="1" />
          <text :x="78 + i * 104" :y="H - 11" class="strip" text-anchor="middle"
                :fill="i === stripIndex ? 'var(--ann-paper)' : 'var(--ann-muted)'">{{ s }}</text>
        </g>
      </g>

      <!-- ============ colour legend, setup slide only ============ -->
      <g v-if="stage === 'setup'" v-click="from + 3">
        <text x="30" :y="H - 66" class="cap fwd">TEAL = FORWARD, what the network computes</text>
        <text x="30" :y="H - 48" class="cap bwd">EMBER = BACKWARD, what the loss demands</text>
        <text x="470" :y="H - 66" class="cap ind">INDIGO = THE UPDATE, where the two meet</text>
        <text x="470" :y="H - 48" class="cap">DASHED CHIP = a per-neuron BIAS, not a weight</text>
      </g>
    </svg>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  stage: { type: String, required: true },
  from: { type: Number, default: 1 },
  showStrip: { type: Boolean, default: true },
  compact: { type: Boolean, default: false },
})

/* ---------------------------------------------------------------
   Verified constants. Source of truth: scripts/verify-numbers.py
   Displayed to 4 significant figures — full precision belongs in the
   speaker notes, not on a projector at the back of a lecture hall.
   --------------------------------------------------------------- */
const V = Object.freeze({
  i1: '0.05', i2: '0.10', t1: '0.01', t2: '0.99',
  w: { w1: '0.15', w2: '0.20', w3: '0.25', w4: '0.30', w5: '0.40', w6: '0.45', w7: '0.50', w8: '0.55' },
  b1: '0.35', b2: '0.60',
  // forward pass is unaffected by the choice of loss
  net_h1: '0.3775', out_h1: '0.5933',
  net_h2: '0.3925', out_h2: '0.5969',
  net_o1: '1.1059', out_o1: '0.7514',
  net_o2: '1.2249', out_o2: '0.7729',
  // MSE  L = 1/2 [ (o1-t1)^2 + (o2-t2)^2 ], computed from UNROUNDED outputs
  E: '0.2984', E_new: '0.2805',
  // delta = (o - t) * o(1 - o)   -- both factors; nothing cancels under MSE
  err_o1: '0.7414', err_o2: '-0.2171',
  resp_o1: '0.1868', resp_o2: '0.1755',
  d_o1: '0.1385', d_o2: '-0.0381',
  g: { w1: '4.39e-4', w2: '8.77e-4', w3: '4.98e-4', w4: '9.95e-4',
       w5: '0.0822', w6: '0.0827', w7: '-0.0226', w8: '-0.0227' },
  gb1a: '0.0088', gb1b: '0.0100',
  up: { w1: '0.1498', w2: '0.1996', w3: '0.2498', w4: '0.2995',
        w5: '0.3589', w6: '0.4087', w7: '0.5113', w8: '0.5614' },
  path1: '0.0554', path2: '-0.0190', sum_h1: '0.0364',
  d_h1: '0.0088', d_h2: '0.0100',
})

const H = computed(() => (props.compact ? 372 : 400))

/* ---------------- geometry ---------------- */
const Y1 = 120, Y2 = 252
const XI = 84, XH = 330, XO = 590, XT = 820

const INPUTS = computed(() => {
  const inClick = clickOf('inputs')          // null unless this stage reveals them
  const tgClick = clickOf('targets')
  const out = [
    { k: 'i1', x: XI, y: Y1, v: V.i1, lbl: 'input 1', click: inBase('inputs') ? null : inClick },
    { k: 'i2', x: XI, y: Y2, v: V.i2, lbl: 'input 2', click: inBase('inputs') ? null : inClick },
  ]
  if (inBase('targets')) {
    out.push({ k: 't1', x: XT, y: Y1, v: V.t1, lbl: 'target 1', click: null },
             { k: 't2', x: XT, y: Y2, v: V.t2, lbl: 'target 2', click: null })
  } else if (tgClick !== null) {
    out.push({ k: 't1', x: XT, y: Y1, v: V.t1, lbl: 'target 1', click: tgClick },
             { k: 't2', x: XT, y: Y2, v: V.t2, lbl: 'target 2', click: tgClick })
  }
  return out.filter(q => q.click !== undefined)
})

const NEURONS = [
  { k: 'h1', x: XH, y: Y1, lbl: 'h1' }, { k: 'h2', x: XH, y: Y2, lbl: 'h2' },
  { k: 'o1', x: XO, y: Y1, lbl: 'o1' }, { k: 'o2', x: XO, y: Y2, lbl: 'o2' },
]

// Wiring follows the arithmetic exactly:
//   net_h1 = w1.i1 + w2.i2     net_h2 = w3.i1 + w4.i2
//   net_o1 = w5.h1 + w6.h2     net_o2 = w7.h1 + w8.h2
// so w2 is i2->h1 (not i1->h2), and w7 is h1->o2 (not h2->o1).
const EDGES = [
  { k: 'w1', x1: XI + 26, y1: Y1, x2: XH - 34, y2: Y1, t: 0.26, gt: 0.5 },
  { k: 'w2', x1: XI + 26, y1: Y2, x2: XH - 34, y2: Y1, t: 0.70, gt: 0.78 },
  { k: 'w3', x1: XI + 26, y1: Y1, x2: XH - 34, y2: Y2, t: 0.54, gt: 0.26 },
  { k: 'w4', x1: XI + 26, y1: Y2, x2: XH - 34, y2: Y2, t: 0.26, gt: 0.5 },
  { k: 'w5', x1: XH + 34, y1: Y1, x2: XO - 34, y2: Y1, t: 0.26, gt: 0.5 },
  { k: 'w6', x1: XH + 34, y1: Y2, x2: XO - 34, y2: Y1, t: 0.70, gt: 0.78 },
  { k: 'w7', x1: XH + 34, y1: Y1, x2: XO - 34, y2: Y2, t: 0.54, gt: 0.22 },
  { k: 'w8', x1: XH + 34, y1: Y2, x2: XO - 34, y2: Y2, t: 0.26, gt: 0.5 },
]
const edge = (k) => EDGES.find((e) => e.k === k)
const at = (k, t) => {
  const e = edge(k)
  return { x: e.x1 + (e.x2 - e.x1) * t, y: e.y1 + (e.y2 - e.y1) * t }
}

/* ---------------- stage choreography ----------------
   base   : on screen at slide load. `dimKeys` fade to 32%.
   reveal : one array per click, in order.
   clicks : the number the host slide MUST declare in frontmatter.
---------------------------------------------------------- */
const FWD = ['net_h', 'out_h', 'net_o', 'out_o', 'weights', 'bias']

const STAGES = {
  // clicks: 4
  setup: { base: [], reveal: [['inputs', 'targets'], ['weights'], ['bias'], ['legend']], strip: 0 },

  // clicks: 5
  'forward-hidden': {
    base: ['inputs', 'weights', 'bias'],
    reveal: [['lit-h1'], ['net_h1'], ['out_h1'], ['net_h2', 'out_h2'], ['unlit']],
    strip: 0,
  },

  // clicks: 5
  'forward-output': {
    base: ['inputs', 'weights', 'bias', 'net_h', 'out_h'],
    reveal: [['lit-o1', 'net_o1'], ['out_o1'], ['net_o2', 'out_o2'], ['targets'], ['loss']],
    strip: 1,
  },

  // clicks: 6  (6th is the slide's own key-message)
  'delta-output': {
    base: ['out_h', 'out_o', 'weights', 'bias', 'inputs', 'targets', 'loss'],
    dim: ['out_h', 'out_o', 'weights', 'bias'],
    reveal: [['lit-back-o'], [], [], ['d_o1'], ['d_o2']],
    strip: 2,
  },

  // clicks: 5  (5th is the slide's own key-message)
  'grad-output': {
    base: ['out_h', 'out_o', 'weights1', 'bias1', 'inputs', 'targets', 'd_o1', 'd_o2'],
    dim: ['out_o', 'bias1', 'weights1'],
    reveal: [['g_w5'], ['g_w678'], [], ['gb_o']],
    strip: 3,
  },

  // clicks: 7
  'delta-hidden': {
    base: ['out_h', 'out_o', 'weights', 'inputs', 'targets', 'd_o1', 'd_o2'],
    dim: ['out_o'],
    reveal: [['lit-h1-out'], ['path1'], ['path2'], ['sum_h1'], ['d_h1'], ['d_h2'], []],
    strip: 4,
  },

  // clicks: 6
  update: {
    base: ['out_h', 'out_o', 'inputs', 'targets', 'd_o1', 'd_o2', 'd_h1', 'd_h2'],
    dim: ['out_h', 'out_o'],
    reveal: [['g_w1'], ['g_w234'], ['gb_h'], ['g_out', 'gb_o'], ['loss_new'], []],
    strip: 5,
  },
}

const STRIP = ['forward', 'loss', 'blame out', 'grads out', 'blame hid', 'update']
const cfg = computed(() => STAGES[props.stage] ?? STAGES.setup)
const stripIndex = computed(() => cfg.value.strip)

const clickOf = (key) => {
  const idx = cfg.value.reveal.findIndex((layer) => layer.includes(key))
  return idx === -1 ? null : props.from + idx
}
const inBase = (key) => cfg.value.base.includes(key)
const isDim = (key) => (cfg.value.dim ?? []).includes(key)

/* edge highlighting */
const lit = (edgeKey) => {
  const s = props.stage
  if (s === 'forward-hidden') return ['w1', 'w2'].includes(edgeKey)
  if (s === 'forward-output') return ['w5', 'w6'].includes(edgeKey)
  if (s === 'delta-hidden') return ['w5', 'w7'].includes(edgeKey)
  return false
}
const litColor = computed(() =>
  props.stage === 'delta-hidden' ? 'var(--ann-ember)' : 'var(--ann-circuit)')
const dimmed = (k) => {
  if (props.stage === 'forward-hidden') return ['o1', 'o2'].includes(k)
  return false
}

/* ---------------- annotation table ----------------
   Each entry: key, x, y, text, css class, optional chip styling.
   Split into base (no directive) and click (v-click bound) so that
   nothing depends on v-click="0" behaving like "always visible".
------------------------------------------------------- */
const CHIP = { fwd: { fill: 'var(--ann-circuit-soft)', stroke: 'var(--ann-circuit)' },
               bwd: { fill: 'var(--ann-ember-soft)', stroke: 'var(--ann-ember)' },
               upd: { fill: 'var(--ann-indigo-soft)', stroke: 'var(--ann-indigo)' },
               // bias: same teal family (it is a forward parameter) but hollow
               // and dashed, so it never reads as a weight on an edge
               bias: { fill: 'var(--ann-paper)', stroke: 'var(--ann-circuit)', dash: '4 3' } }

function build() {
  const out = []
  // width follows the text: JetBrains Mono at 16px advances ~9.7px/char
  const autoW = (t) => Math.max(50, Math.round(String(t).length * 9.7 + 16))
  const add = (k, x, y, t, cls, chip = null, w = null) => {
    out.push({ k, x, y, t, cls, chip: !!chip, w: w ?? autoW(t), ...(chip ? CHIP[chip] : {}) })
  }

  // inputs group is drawn separately; here: weights, biases, per-neuron slots
  for (const e of EDGES) {
    const p = at(e.k, e.t)
    add('weights:' + e.k, p.x, p.y, V.w[e.k], 'fwd', 'fwd', 54)
  }
  add('bias:b1a', XH + 78, Y1 - 30, 'b ' + V.b1, 'fwd', 'bias', 74)
  add('bias:b1b', XH + 78, Y2 - 30, 'b ' + V.b1, 'fwd', 'bias', 74)
  add('bias:b2a', XO + 78, Y1 - 30, 'b ' + V.b2, 'fwd', 'bias', 74)
  add('bias:b2b', XO + 78, Y2 - 30, 'b ' + V.b2, 'fwd', 'bias', 74)

  add('net_h:1', XH, Y1 - 76, V.net_h1, 'fwd')
  add('net_h:2', XH, Y2 - 76, V.net_h2, 'fwd')
  add('out_h:1', XH, Y1, V.out_h1, 'ink')
  add('out_h:2', XH, Y2, V.out_h2, 'ink')
  add('net_o:1', XO, Y1 - 76, V.net_o1, 'fwd')
  add('net_o:2', XO, Y2 - 76, V.net_o2, 'fwd')
  add('out_o:1', XO, Y1, V.out_o1, 'ink')
  add('out_o:2', XO, Y2, V.out_o2, 'ink')

  add('d_o1', XO, Y1 + 56, V.d_o1, 'bwd', 'bwd')
  add('d_o2', XO, Y2 + 56, V.d_o2, 'bwd', 'bwd')
  add('d_h1', XH, Y1 + 56, V.d_h1, 'bwd', 'bwd')
  add('d_h2', XH, Y2 + 56, V.d_h2, 'bwd', 'bwd')

  // gradients sit at each edge's own gt, chosen to clear that edge's weight label
  for (const e of EDGES) {
    const p = at(e.k, e.gt)
    add('grad:' + e.k, p.x, p.y, V.g[e.k], 'bwd', 'bwd')
  }

  add('gb_o:a', XO + 86, Y1 - 30, '∂b ' + V.d_o1, 'bwd', 'bwd', 92)
  add('gb_o:b', XO + 86, Y2 - 30, '∂b ' + V.d_o2, 'bwd', 'bwd', 92)
  add('gb_h:a', XH + 86, Y1 - 30, '∂b ' + V.gb1a, 'bwd', 'bwd', 92)
  add('gb_h:b', XH + 86, Y2 - 30, '∂b ' + V.gb1b, 'bwd', 'bwd', 92)

  // the two backward paths into h1, and their sum
  add('path1', (XH + XO) / 2 + 10, Y1 - 34, V.path1, 'bwd', 'bwd', 62)
  add('path2', (XH + XO) / 2 - 34, (Y1 + Y2) / 2 + 40, V.path2, 'bwd', 'bwd', 62)
  add('sum_h1', XH - 4, Y1 - 100, V.sum_h1, 'bwd', 'bwd', 70)
  return out
}
const ALL = build()

/* which annotation keys belong to which stage key */
const GROUPS = {
  weights: EDGES.map((e) => 'weights:' + e.k),
  weights1: ['w1','w2','w3','w4'].map((k) => 'weights:' + k),
  weights2: ['w5','w6','w7','w8'].map((k) => 'weights:' + k),
  bias: ['bias:b1a', 'bias:b1b', 'bias:b2a', 'bias:b2b'],
  bias1: ['bias:b1a', 'bias:b1b'],
  bias2: ['bias:b2a', 'bias:b2b'],
  net_h: ['net_h:1', 'net_h:2'], out_h: ['out_h:1', 'out_h:2'],
  net_o: ['net_o:1', 'net_o:2'], out_o: ['out_o:1', 'out_o:2'],
  net_h1: ['net_h:1'], out_h1: ['out_h:1'], net_h2: ['net_h:2'], out_h2: ['out_h:2'],
  net_o1: ['net_o:1'], out_o1: ['out_o:1'], net_o2: ['net_o:2'], out_o2: ['out_o:2'],
  d_o1: ['d_o1'], d_o2: ['d_o2'], d_h1: ['d_h1'], d_h2: ['d_h2'],
  g_w5: ['grad:w5'], g_w678: ['grad:w6', 'grad:w7', 'grad:w8'],
  g_w1: ['grad:w1'], g_w234: ['grad:w2', 'grad:w3', 'grad:w4'],
  g_out: ['grad:w5', 'grad:w6', 'grad:w7', 'grad:w8'],
  gb_o: ['gb_o:a', 'gb_o:b'], gb_h: ['gb_h:a', 'gb_h:b'],
  path1: ['path1'], path2: ['path2'], sum_h1: ['sum_h1'],
}
const expand = (key) => GROUPS[key] ?? []

const baseKeys = computed(() => new Set(cfg.value.base.flatMap(expand)))
const dimKeys = computed(() => new Set((cfg.value.dim ?? []).flatMap(expand)))

const clickMap = computed(() => {
  const m = new Map()
  cfg.value.reveal.forEach((layer, i) => {
    layer.forEach((key) => expand(key).forEach((ak) => m.set(ak, props.from + i)))
  })
  return m
})

const baseAnnos = computed(() =>
  ALL.filter((a) => baseKeys.value.has(a.k) && !clickMap.value.has(a.k))
     .map((a) => ({ ...a, dim: dimKeys.value.has(a.k) })))

const clickAnnos = computed(() =>
  ALL.filter((a) => clickMap.value.has(a.k))
     .map((a) => ({ ...a, click: clickMap.value.get(a.k) })))

const lossBox = computed(() => {
  if (clickOf('loss_new') !== null) return { t: V.E_new, click: clickOf('loss_new') }
  if (clickOf('loss') !== null) return { t: V.E, click: clickOf('loss') }
  if (inBase('loss')) return { t: V.E, click: props.from - 1 }
  return null
})
</script>

<style scoped>
.bptrace { width: 100%; }
.bptrace svg { width: 100%; height: auto; display: block; max-height: 40vh; }
.bptrace.is-compact svg { max-height: 33vh; }

.val {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 17px;
  font-variant-numeric: tabular-nums;
}
/* bias and bias-gradient chips carry a name as well as a number */
.val.fwd, .val.bwd { font-size: 16px; }
.val.ink { fill: var(--ann-ink); font-weight: 700; font-size: 19px; }
.val.fwd { fill: var(--ann-circuit); }
.val.bwd { fill: var(--ann-ember); }
.val.upd { fill: var(--ann-indigo); font-weight: 600; }

.nname {
  font-family: 'Space Grotesk', sans-serif;
  font-size: 17px;
  font-weight: 700;
  fill: var(--ann-ink-soft);
}

.cap {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 11px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  fill: var(--ann-muted);
}
.cap.fwd { fill: var(--ann-circuit); }
.cap.bwd { fill: var(--ann-ember); }
.cap.ind { fill: var(--ann-indigo); }

.strip {
  font-family: 'JetBrains Mono', ui-monospace, monospace;
  font-size: 9px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}
</style>
